### ISSUE TITLE
<blockquote> style is too much

### ISSUE THREAD

**Issue by hftf** [nmartin84/logseq-solarized#3]
Thank you for this theme!

I find the `<blockquote>` style rather intrusive. While I understand this is only a personal opinion and that design is subjective, I also try to approach assessing a theme via how can it most inclusively fit a general-purpose user base. I will first describe what I believe is the most general use case for blockquotes (so as to inform the design), followed by the issues in the design.

The blockquote syntax `>` is one of the only methods available for representing quoted or non-original text excerpts (besides quotation marks `"`, which are part of the text itself and not a manipulable element). I imagine that a very common workflow when reading an article or text is: to type `>`, paste a snippet of text from the original source, and then write own commentary in new blocks indented below. Thus, I would be surprised if most users use blockquotes for a "pullquote"-style affordance, i.e. specifically with the intent to emphasize and draw attention rather than just mark. (Relevant case study: Notion has a pullquote block, but until recently the only default style was 125% font size, italic, faded gray text. After listening to customer feedback for maybe 3 years, they cut back the default to have fewer styles and added an option for larger font size; see [here](https://twitter.com/NotionHQ/status/1412858147379703808).)

Poor experience occurs when the icon font for the fancy oversized quotation marks `❝❠` doesn't load. However, my suggestion is not to take this as a sign that a bug should be ironed out or an alternative icon be found, but that an icon is really not actually needed and can be removed. (In contrast, a "functional" icon is a `🞩` "close" button or a `►` delimiter between breadcrumbs.)

<img width="925" alt="Screen Shot 2021-09-15 at 17 53 42" src="https://user-images.githubusercontent.com/312957/133517812-6b086d6c-8dfc-4acf-a77c-ab0689a37faa.png">

Center alignment and horizontal padding: these not only cause readability to suffer, but specifically in an outliner, which is all about indentation, it misleads you about where the indentation level is. It awkwardly strands the bullet point `•`, but bullets are so core in an outliner: they are actually functional interface elements, and should be "right next to" their block. The box always seems slightly off-center, as it can't really be perfectly centered anyway due to the indentation and no reciprocal right padding. Intentionally not using the full width also wastes precious screen real estate. I would rather privilege my notes to take up the most space, not the interface or the aesthetics. Indentation, i.e. space, also has a core meaning, and should not be played with nonchalantly.

**Comment by nmartin84** [comment]
I haven't messed with this theme in awhile, but I agree it needs some more lovin and fixes, let me take a look at this later today and see if I can get this fixed along with some other items. Thanks for the feedback!

**Comment by nmartin84** [comment]
This should be fixed now -- i've migrated this theme to the new format i've used in the tokyo-night theme, but may re-visit and see if I can find a cleaner approach for styling block quotes.
